name: 💨 Smoke Test - Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies and fire up docker-compose
      run: make create

    - name: Create Kafka Topic
      run: make topic

    - name: Create Pinot Tables
      run: make tables

    - name: Import Data
      run: make import

    #TODO: add step to check REST url of query console
    
    - name: Testdown
      run: make destroy
